spring:
  datasource:
    url: jdbc:postgresql://product-db.ct4ogyo2wvaz.us-east-2.rds.amazonaws.com:5432/productdb
    username: ankit
    password: ankit12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create' to generate tables, 'update' to modify existing ones, or 'none' to do it manually
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
cloud:
  aws:
    credentials:
      use-default-aws-credentials-chain: true
    region:
      static: us-east-1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health