spring:
  datasource:
    url: jdbc:mysql://test.ct4ogyo2wvaz.us-east-2.rds.amazonaws.com:3306/ProductDB
    username: ankit
    password: ankit12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create' to generate tables, 'update' to modify, or 'none' for manual
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    region:
      static: us-east-1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health