spring:
    datasource:
      url: jdbc:postgresql://product-db.ct4ogyo2wvaz.us-east-2.rds.amazonaws.com:5432/productdb
      username: ankit
      password: ankit12345
      driver-class-name: org.postgresql.Driver
cloud:
  aws:
    credentials:
      use-default-aws-credentials-chain: true
    region:
      static: us-east-1
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true